name: PlatformIO CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        example: [showcontrol_refactor]
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install PlatformIO Core
      run: pip install --upgrade platformio
    
    - name: Build PlatformIO Project
      run: pio run
      
    - name: Run Tests
      run: pio test --verbose
      
    - name: Build filesystem
      run: pio run --target buildfs
